version: 2

sources:
  - name: airbytes_test
    description: "testing airbytes using dbt"
    database: airflow
    schema: public
    tables:
      - name: dbt_test
        description: "details about students"
