version: 2

sources:
  - name: airbytes_test
    description: "testing airbytes using dbt"
    database: public
    schema: dbt_demo
    tables:
      - name: dbt_test
        description: "details about students"